# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 09f1911f9d3490a6aca3f63a94d81eae8f26cc6e13f01db7830103eabf7d5b8ea74eecc19500262142fb59a3721c332c95e0a336f6687988b336809af5411300

test:
  secret_key_base: 723a8b64b0c83cd46d638ae1788b01d1a0eba41fac03002e6ce3e5ce0cd2ac0ca682db0bfbfa70cc9205561ec4cc4ab4a143623633a6a691b5a20f5145ac527d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
